version: '3'

name: maxbittgbot

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    restart: always
    environment:
      POSTGRES_DB: maxbitdb
      POSTGRES_USER: maxbituser
      POSTGRES_PASSWORD: maxbitpassword
    ports:
      - "5432:5432"
    networks:
      - maxbitnetwork

  app:
    restart: always
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    networks:
      - maxbitnetwork
    environment:
      - DB_HOST=postgres

networks:
  maxbitnetwork: